receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 100
    timeout: 10s

exporters:
  datadog:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE}
  otlphttp/jaeger:
    endpoint: http://jaeger.spring-datadog-lab.svc.cluster.local:4318
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, otlphttp/jaeger, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog, debug]